### ISSUE TITLE
Back Button error

### ISSUE THREAD

**Issue by 7xopoulos** [MosheBerman/MBCalendarKit#100]
Hi,

I am using MBCalendar for my app. When I use Week View and I tap the back button my app is terminating with the error below. Any ideas?

```
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
```

**Comment by MosheBerman** [comment]
Which date(s) were visible? What mode was the calendar in? Some more information would be helpful.

**Comment by 7xopoulos** [comment]
Sorry for the delay. It was a silly mistake of mine. One more question can the calendar be localized in Greek? I tried with set locale but with no luck. I am newbie in ios apps.

Thank you for your time.

**Comment by MosheBerman** [comment]
Look at the NSLocale and NSCalendar properties.
