### ISSUE TITLE
Crash - Xcode 7.1.1 Demo App

### ISSUE THREAD

**Issue by sairamkotha** [MosheBerman/MBCalendarKit#101]
while running demo app (objective C ) app is not even opening. I commented all setDelegate functions then app is running but when i clicked on event it is not opening. Please help me.

-[CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance 0x14e62c6a0
2015-11-30 20:11:42.481 MBCalendarKit[861:168117] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance 0x14e62c6a0'

**Comment by sairamkotha** [comment]
another crash
-[CKCalendarViewControllerInternal delegate]: unrecognized selector sent to instance 0x126535b50
2015-11-30 20:15:58.299 MBCalendarKit[869:169277] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CKCalendarViewControllerInternal delegate]: unrecognized selector sent to instance 0x126535b50'

**Comment by MosheBerman** [comment]
Can you show me what your code looks like when you commented out the setDelegate methods?

**Comment by sairamkotha** [comment]
Actually I am using example on Xcode 7.1.1. It is now even opening. It crashed after opening with error CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance

**Comment by sairamkotha** [comment]
<img width="1280" alt="screen shot 2015-12-01 at 1 31 54 am" src="https://cloud.githubusercontent.com/assets/12541774/11482883/58dc6fd4-97cb-11e5-8302-97fe4dc2754c.png">
I didnt changed any code I got this error

**Comment by sairamkotha** [comment]
<img width="1280" alt="screen shot 2015-12-01 at 1 34 08 am" src="https://cloud.githubusercontent.com/assets/12541774/11482952/ac789172-97cb-11e5-837e-3cec475969af.png">

when I commented this line //    [[self calendarView] setDelegate:self]; in CKCalendarViewControllerInternal this is the error

**Comment by sairamkotha** [comment]
//        [_calendarViewController setDelegate:self];
// [[self calendarView] setDelegate:self]; both lines are commented it is not crashed but when I clicked on event nothing happening.I don't know why it is happening.Help me

**Comment by MosheBerman** [comment]
If you commented out those methods, there's a good chance that the delegate wasn't being called which is why nothing is happening.

If you're seeing an error when the delegate methods are not commented out, it probably means you changed something else. I'm going to take a look, but the code should be working out of the box.

Have you made any other changes?

**Comment by sairamkotha** [comment]
I didn't changed any part of code I just cloned your repository and Opened "MBCalendarKit.xcodeproj" this file. Installed mbcalendarkit using xcode 7.1.1 on iphone 9.0.2 device. It crashed with this runtime error CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance

**Comment by MosheBerman** [comment]
Ok, I'm going to take a look.

**Comment by sairamkotha** [comment]
Okay

**Comment by sairamkotha** [comment]
Did you able to reproduce the issue that I have said ?

**Comment by sairamkotha** [comment]
Status ?

**Comment by jiemi** [comment]
I have the same problem....too

**Comment by sairamkotha** [comment]
Same issue. No reply from him.

**Comment by akifbilal** [comment]
Go to CKCalendarViewControllerInternal.m and replace @dynamic delegate; with @synthesize delegate;

**Comment by akifbilal** [comment]
It will resolve your issue.

**Comment by railsfactory-kumaresh** [comment]
yeah after replace @dynamic delegate with @synthesize delegate. It working fine. 
Thanks akifbilal.

But this changes should merge with master........

**Comment by MosheBerman** [comment]
Fixed in #107.

**Comment by akifbilal** [comment]
Great
