### ISSUE TITLE
Lunar Date

### ISSUE THREAD

**Issue by mohsinalimat** [MosheBerman/MBCalendarKit#103]
Hi,
how to implement Lunar Date in your calendar?

**Comment by MosheBerman** [comment]
There are several lunar calendars in iOS. There's Hebrew calendar, as well as several islamic calendars. Set the `calendar` property of the `CKCalendarView` to an instance of NSCalendar, like so:

```
NSCalendar *hebrewCalendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierHebrew];

self.calendarView.calendar = hebrewCalendar;
```

**Comment by iChernov** [comment]
Trying to do that in the Demo app - either I do miss something, or I'm writing your proposed solution in a wrong file - but as I saw the usual gregorian calendar before - as I see it now...

**Comment by iChernov** [comment]
In other words - old receipt doesn't't work anymore (or I am stupid enough to use it in a wrong way)

**Comment by iChernov** [comment]
In your demo app - very simple - how can I set the hebrew (or any other alternative) calendar?

**Comment by MosheBerman** [comment]
@iChernov That should be how to do it - if it's not working, then you might be running into a bug. You should be able to set the calendar property on the calendar view. Can you share your code that you're using?

Side note: There's a new version of the library that's almost done, which I've just confirmed has this working. If you can wait a little bit, I'll wrap up the release and ship it.

**Comment by iChernov** [comment]
Okay, if I am so lucky that the new version is just around the corner - let me just wait a bit :)

**Comment by iChernov** [comment]
@MosheBerman 
What I tried: 
    [[self calendarView] setCalendar:[NSCalendar calendarWithIdentifier:NSCalendarIdentifierHebrew]];
in CKCalendarViewControllerInternal of your example app. Doesn't work. In viewDidLoad method of CKDemoViewController calendarView property is still nil. No ideas - where exactly to set it then.
