### ISSUE TITLE
App crash on Launch

### ISSUE THREAD

**Issue by railsfactory-kumaresh** [MosheBerman/MBCalendarKit#104]
-[CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance 0x7fc5f960c0e0
2016-01-22 10:29:18.559 MBCalendarKit[75717:6985114] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CKCalendarViewControllerInternal setDelegate:]: unrecognized selector sent to instance 0x7fc5f960c0e0'

Please fix this issue ASAP.

**Comment by xzysun** [comment]
face the same problem

**Comment by MosheBerman** [comment]
What setup did you do to produce this issue? Steps to reproduce?

**Comment by xzysun** [comment]
@MosheBerman   I had changed `@dynamic delegate;` in CKCalendarViewControllerInternal to `@synthesize delegate;` , so the application can launch successfully.

**Comment by MosheBerman** [comment]
Would you mind submitting a pull request with the fix?

**Comment by MosheBerman** [comment]
Should be fixed with #107.
