### ISSUE TITLE
Not able to click last day in WeekView when calendarView.firstWeekDay = 2 or 3;

### ISSUE THREAD

**Issue by narendra-ct** [MosheBerman/MBCalendarKit#106]
Hi,

I have an issue with MBCalendarKit , when i change my calendarView.firstWeekDay = 2 or when i change my region "**netherland**" from iPhone settings, application is not allowing us to click last day of week.Please have a look on this.

Please find attached image for more info.
![thumb_img_4393_1024](https://cloud.githubusercontent.com/assets/5906472/12812002/0bc1bd30-cb56-11e5-8a0e-eb32e34143b5.jpg)

**Comment by MosheBerman** [comment]
Thanks for filing. Can you provide a code sample or sample Xcode project?

**Comment by narendra-ct** [comment]
PFA sample xcode project, and try to click
[CalendarKit.zip](https://github.com/MosheBerman/MBCalendarKit/files/118681/CalendarKit.zip)
 on Sunday (day) on weekview.

**Comment by MosheBerman** [comment]
MBCalendarKit 5 includes a heavily modified calendar view, so please try it and see how it works. If you have any more questions, please feel free to comment here and we can re-open this issue.
