### ISSUE TITLE
Problem when showing the calendar on iPhone 6s Plus not in Simulator

### ISSUE THREAD

**Issue by magcp** [MosheBerman/MBCalendarKit#110]
I have an issue that the first row of days in the monthly view is not showing up, in Simulator it works fine but on my device it's not as below screenshots:
This is the simulator:
<img width="306" alt="ok" src="https://cloud.githubusercontent.com/assets/4884757/14950506/c7f953ac-105a-11e6-91ea-3bfd77ca8bb3.png">

And this is on my phone:
![not](https://cloud.githubusercontent.com/assets/4884757/14950498/b4d51612-105a-11e6-9ae1-72c17033aaec.png)

Any ideas?

**Comment by MosheBerman** [comment]
That's interesting. It seems that the rest of your screen is scaled down too. 

If you use Xcode's inspector to show the layers of the screen, I think you might see the top row behind the header row. 

![screen shot 2016-05-02 at 8 49 04 am](https://cloud.githubusercontent.com/assets/427452/14954750/e876f7a0-1042-11e6-9ca4-5111f0f5bb1b.png)

The screen scaling probably has nothing to do with MBCalendarKit, but I can't be sure unless I can see some code and/or screenshots from Xcode's Debug View Hierarchy.

**Comment by magcp** [comment]
Hi, Thanks, I can provide you whatever you like, the Debug View Hierarchy is attached,
 
![image](https://cloud.githubusercontent.com/assets/4884757/14976721/d38a6c4e-1116-11e6-94fc-7d67fe930ae2.png)


Thank you,

**Comment by magcp** [comment]
Hello Moshe,

Any updates? or suggestions?

Thank you in advance,

**Comment by MosheBerman** [comment]
This looks related to #73, but I don't have any updates for you at this time. 

MBCalendarKit is a side project, and I don't have a lot of time right now to dive in and fix things. If you'd like, feel free to have a go at the rendering code in the CKCalendarView class - I suspect that is where the problem lies.

**Comment by magcp** [comment]
OK Thanks, for a temporary fix 
I have returned the "firstOfTheMonth" variable as this was the problem,


- (NSDate *)_firstVisibleDateForDisplayMode:(CKCalendarDisplayMode)displayMode
{
    // for the day mode, just return today
    if (displayMode == CKCalendarViewModeDay) {
        return [self date];
    }
    else if(displayMode == CKCalendarViewModeWeek)
    {
        return [[self calendar] firstDayOfTheWeekUsingReferenceDate:[self date] andStartDay:self.calendar.firstWeekday];
    }
    else if(displayMode == CKCalendarViewModeMonth)
    {
    **    NSDate *firstOfTheMonth = [[self calendar] firstDayOfTheMonthUsingReferenceDate:[self date]];
        return firstOfTheMonth;**
    }
    
    return [self date];
}

**Comment by MosheBerman** [comment]
Thanks. I'll use this info when investigating.

**Comment by MosheBerman** [comment]
This thread is old, but MBCalendarKit just hit version 5.0.0 today, and it includes auto layout support. I did notice this bug specifically when using an Arabic locale to display the calendar, so I'm going to debug this when I have some time.

**Comment by magcp** [comment]
Hi, thanks for the heads up
Waiting for it

Regards

**Comment by MosheBerman** [comment]
This should be fixed in 5.1.0. Please take a look and let me know.
