### ISSUE TITLE
What about time's for the events?

### ISSUE THREAD

**Issue by johnheb** [MosheBerman/MBCalendarKit#114]
Seems like a solid and well thought out app.  Is there any way to accommodate times on the dates?

**Comment by MosheBerman** [comment]
I'm sorry for the late reply, if you're still interested, can you provide a screenshot with an annotation pointing out what you want? If not (and I wouldn't be surprised) would you mind closing this issue?

**Comment by MosheBerman** [comment]
I'm closing this issue because it's pretty old and haven't gotten a reply back.
