### ISSUE TITLE
The fresh created calendarView is cut at the very top

### ISSUE THREAD

**Issue by iChernov** [MosheBerman/MBCalendarKit#119]
Modally presented ViewController, the only thing is done - in viewDidLoad method added the CalendarView. As you can see (see photo attached) - the top line of numbers is cut. Seems like it is added to the view without respect of TopLayoutGuide... at least I assume so.

<img width="423" alt="screen shot 2017-08-16 at 20 59 06" src="https://user-images.githubusercontent.com/6980914/29380385-d968b43c-82c5-11e7-9808-25b7a03d62ab.png">

**Comment by MosheBerman** [comment]
Yup, this is because MBCalendarKit 4.0.1 doesn't support autolayout properly. You can work around this for now by turning off `automaticallyAdjustsContentInsets` on your view controller. 

Thanks for reporting this. It's also going to be fixed in 5.0.0. 

Related issues: #109 #108 #118

**Comment by iChernov** [comment]
@MosheBerman You mentioned that 5.0.0 is around the corner - can you tell a bit more concrete - when it will happen?..

**Comment by MosheBerman** [comment]
I don't want to commit to a specific day, but I need this for a couple of side projects, so I've been working on this since the end of July. Probably a couple of days tops. Trying to round everything out, and make sure it all works right.

**Comment by iChernov** [comment]
@MosheBerman I meant more months - in August, in September... no strict dates :)

**Comment by MosheBerman** [comment]
5.0.0 was just released. Cocoapods should be propagating now.

**Comment by MosheBerman** [comment]
(Please let me know if this can be closed.)

**Comment by MosheBerman** [comment]
@iChernov Is this still an issue with 5.0.x?

**Comment by iChernov** [comment]
Wasn't able to check it yet - will do that on this weekend!

**Comment by MosheBerman** [comment]
It's been a couple of weekends. 😄  Any luck?

**Comment by iChernov** [comment]
Am... now it's even worse. It ignores .calendar.firstWeekday parameter. Now it is ALWAYS Sunday. Current version is 5.0.4

**Comment by MosheBerman** [comment]
Great!
