### ISSUE TITLE
CKCalendarView appearing behind iOS 7 status bar

### ISSUE THREAD

**Issue by ed-parry** [MosheBerman/MBCalendarKit#37]
This is a similar issue to having a `UITableView` on a `UIView` in iOS 7, where the `UITableView` starts too high and is behind the status bar. When I put a `CKCalendarView` on a `UIView`, the calendar starts behind the status bar, too. I can't seem to figure out a way of pushing it down by 64-pixels to be in the correct place. Is there something I'm missing?

![CKCalendarView Issue](https://f.cloud.github.com/assets/514825/2150456/71c96b3e-9401-11e3-8d33-5c16b085d11b.png)

**Comment by griffind** [comment]
I fixed this by adding 
```objective-c
calendar.frame = CGRectOffset(self.view.frame, 0.0, 65.0);
```
to the viewDidLoad

**Comment by bendparker** [comment]
I'm still experiencing it...using griffind's solution for now.

**Comment by bendparker** [comment]
Would be nice to have it fixed, but the work around is okay for now.

Also--I can't seem to initiate an instance of class CKCalendarViewControllerInternal, do I need to import another file for that?

**Comment by MosheBerman** [comment]
The internal view controller needs to be imported separately. It's imported in the public version of the view controller, which subclasses UINavigationController instead of UIViewController. It's otherwise the same thing.
