### ISSUE TITLE
CalendarKit does not install correctly from 2.0.0 cocoapod

### ISSUE THREAD

**Issue by vincilbishop** [MosheBerman/MBCalendarKit#48]
When using:
`pod 'MBCalendarKit', '~>2.0.0'`
Not all of the source files are included in the project.

Changed to:
`pod 'MBCalendarKit', :git => 'https://github.com/MosheBerman/MBCalendarKit'`
And that seems to work.

Looks like the source files are off in the podspec in trunk, looking in a Classes directory.

**Comment by seenickcode** [comment]
Hello, I'm a new user following the instructions using CocoaPods in a new Swift project for XCode 6.3.  I'm getting a "CalendarKit.h file not found" error when importing it in my <projectname>-Bridging-Header.h

I figured out the following fix:
1.  Project > Build Settings > User Header Search Paths > add "${PODS_ROOT}/Headers" and select "recursive"
2.  Including that CKDemo....h file in your <projectname>-Bridging-Header.h will not work, so remove it so this is what is imported:
````
#import "CalendarKit.h"
#import "NSCalendarCategories.h"
#import "NSDate+Components.h"
````

You should then no longer see the error.

I recommend updating the README with this fix.

Thanks!

**Comment by MosheBerman** [comment]
I've assigned myself - when I have a moment, I'll verify and take care of this. Thanks!

**Comment by seenickcode** [comment]
Thanks!
