### ISSUE TITLE
Feature Request: Method to change the dot color

### ISSUE THREAD

**Issue by bci** [MosheBerman/MBCalendarKit#49]
Can be part of CKCalendarDataSource.h:

```
- (UIColor *)calendarView:(CKCalendarView *)calendarView dotColorForDate:(NSDate *)date;
```

I'll try this (and maybe `calendarView:labelColorForDate`, and `calendarView:backgroundColorForDate`), I need to learn more ;) I'm just afraid the code will not be as clean...

**Comment by jarrillaga** [comment]
Hi Moshe, is it possible to have dots with different colors in the actual version?

**Comment by jarrillaga** [comment]
Hi Moshe, the calendar that I need to implement must deal with two types of events. For one I have to paint the cell with a color and for the other I need another color. How can I change the cells colors? Thanks, I really appreciate all your work

**Comment by MosheBerman** [comment]
MBCalendarKit 5.0.0 allows for a lot more customization with the cells. Check out the Custom Cell Provider section of the updated readme for more. Since this issue is really old, I'm going to close it. Feel free to comment here with more thoughts, or open a new issue.
