### ISSUE TITLE
Trouble Linking

### ISSUE THREAD

**Issue by asifhabib** [MosheBerman/MBCalendarKit#59]
Can anyone help me! 
![screen shot 2014-10-02 at 6 47 08 pm](https://cloud.githubusercontent.com/assets/3713433/4491757/80bdf15a-4a3b-11e4-8dd2-8cf8dc33cd71.png)

**Comment by MosheBerman** [comment]
What was the issue with linking? I'm running into it myself.

**Comment by turbocms** [comment]
@MosheBerman In my case, I was including too much in my project. I had to only include the contents of CalendarKit, not MBCalendarKit (which is the parent folder.)

**Comment by MosheBerman** [comment]
Right, thanks. It looks like various versions of Xcode handle linking differently, and I had to link UIKit, CoreGraphics, and Quartz manually.
