### ISSUE TITLE
Swift - Expected a type

### ISSUE THREAD

**Issue by RonGafni** [MosheBerman/MBCalendarKit#63]
Hey,

- (UIColor *)toColor give error: Expected a type.

**Comment by MosheBerman** [comment]
הוספתי demo בסוויפט: SwiftDemoViewController.swift וגם תיקנתי הבאג מקורי שלך.

בבקשה להגיד לי עם 3.0.1 עובד לך. עם כן, רוצה לסגור.

קרוב לשבת כאן בניו יורק. שבת שלום.
