### ISSUE TITLE
NSCalendar+Ranges deprecation warnings

### ISSUE THREAD

**Issue by UberJason** [MosheBerman/MBCalendarKit#65]
Several methods in NSCalendar+Ranges use NSWeekCalendarUnit. In iOS 8, they give deprecation warnings:

'NSWeekCalendarUnit is deprecated: first deprecated in iOS 8.0 - use NSCalendarUnitWeekOfMonth or NSCalendarUnitWeekOfYear, depending on which you mean

Any chance of fixing these deprecations?

**Comment by MosheBerman** [comment]
Those should be `NSCalendarUnitWeekOfYear`, I think, but I have to double check. I'm on it.

**Comment by UberJason** [comment]
Hey there! Wondering if you had a chance to double check and can confirm it should be NSCalendarUnitWeekOfYear? Thanks for looking into it!

**Comment by MosheBerman** [comment]
Fixed in version 3.0.3.

**Comment by MosheBerman** [comment]
Thanks for the feedback!

**Comment by UberJason** [comment]
Thanks!
