### ISSUE TITLE
Calendar cell not render correctly in IOS8

### ISSUE THREAD

**Issue by nqhuycmc** [MosheBerman/MBCalendarKit#66]
Calendar cell not render correctly in IOS8. Help me fix it, thanks.

**Comment by MosheBerman** [comment]
Screenshot please? Sample code?

**Comment by nqhuycmc** [comment]
I've just run your project in simulator Iphone6 IOS8. And it didn't show
cell of each day in month.

**Comment by MosheBerman** [comment]
Did you make any changes to the sample code? Are you trying to show events in the cells? Works for me.

**Comment by nqhuycmc** [comment]
close it, i've used release ver 2.2.6.
