### ISSUE TITLE
Release 3.0.3 not available on Cocoapods

### ISSUE THREAD

**Issue by glentregoning** [MosheBerman/MBCalendarKit#67]
Currently the latest release of MBCalendarKit available via Cocoapods is 2.2.7

E.g. 
 - http://cocoapods.org/?q=MBCalendarKit
 - https://github.com/CocoaPods/Specs/blob/master/Specs/MBCalendarKit/2.2.7/MBCalendarKit.podspec.json

It would be great if you could update the podspec and push it to Cocoapods trunk.

**Comment by MosheBerman** [comment]
I merged your change, but then created and pushed a new pod for 3.0.4, so we should be good to go. Let me know if 3.0.4 works for you with CocoaPods, please. 

The new pod spec appears on GitHub, but not yet on search. I imagine it takes time to propagate.

-  http://cocoapods.org/?q=MBCalendarKit
- https://github.com/CocoaPods/Specs/tree/master/Specs/MBCalendarKit

**Comment by MosheBerman** [comment]
After confirming that the 3.0.4 pod appears in both the GitHub repo and the search, I'm closing this issue. If you still have trouble, please leave a comment and we can revisit this.

**Comment by glentregoning** [comment]
Great thanks!
