### ISSUE TITLE
CalendarView not showing anything

### ISSUE THREAD

**Issue by Schaefers** [MosheBerman/MBCalendarKit#70]
I just tried to implement the CalendarView in a UIViewController Subclass, using this code in the viewDidLoad Method:

``` objective-c
CKCalendarView *calendar = [CKCalendarView new];
    [calendar updateConstraints];
    [calendar setDelegate:self];
    [calendar setDataSource:self];
    [[self view] addSubview:calendar];
```

but the CalendarView is showing up like this

![Image](http://212.227.96.13/Bug.tiff)

Sorry for the huge image, but I don't know how to set it in a spoiler...

**Comment by MosheBerman** [comment]
Calendarkit doesn't use Autolayout. You're calling `updateConstraints` And I bet that is causing the issue. There's another method to invoke the layout routine. Have a look at the calendar view for info on what it is - I'm on my phone at the moment.

**Comment by Schaefers** [comment]
even without calling `updateConstraints` it looks the same way. I don't know how to invoke the layout routine, would be nice if you could have a look at it!

**Comment by MosheBerman** [comment]
So I took another look and it I see the issue. It seems that auto layout isn't playing nicely with the calendar view.

Can you try constructing your app to use the CKCalendarViewController and see what happens?

Side note: The type error is totally unrelated - you need to import UIKit in the color category that is complaining. (Please open a separate issue for that, so I can track it.)

**Comment by vishw3** [comment]
same issue here any work around for this

**Comment by linkcrux** [comment]
I tried with the latest codebase and the issue still exists. Work around plz

**Comment by MosheBerman** [comment]
For now, the workaround is to turn off auto layout.

**Comment by MosheBerman** [comment]
Related: #108

**Comment by MosheBerman** [comment]
This thread is old, but MBCalendarKit just hit version 5.0.0 today, and it includes auto layout support. Give it a shot and report back. Because this issue is so old, I'm going to close it, and you can feel free to re-open if necessary.
