### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by kiahop** [MosheBerman/MBCalendarKit#72]
Thanks for the most up to date and useful calendar control.  I used both methods of implementation, but each seems to have some limitations that I have not been able to get to work.

- When using instance of CKCalendarView, everything works except the 'Today' button and 'Month/Week/Day' selector didn't work.

- When I create an instance of CKCalendarViewController, everything works perfectly.  The only issue is the control covers the top Navigation Bar, and the 'Back' button.  Can you make a suggestion to how to access the Back button?

Thanks

Kia

**Comment by MosheBerman** [comment]
Can you please clarify what you mean by "didn't work?" (For the today button, it simply sets the calendar view's date to `[NSDate date]` and the selector changes the mode.

The `CKCalendarViewController` subclasses `UINavigationController`. There's another class called `CKCalendarViewControllerInternal` which is essentially the same thing, but it's a vanilla UIViewController subclass. 

If you can provide a screenshot of "covers the top of the navigation bar" I would be better able to debug it.

Thanks!

**Comment by kiahop** [comment]
This is the implementation using instance of CKCalendarView method:

![screen shot 2015-03-03 at 5 09 34 pm](https://cloud.githubusercontent.com/assets/10413220/6476242/63cddb82-c1c8-11e4-85b1-f0bafb9d6c14.png)

I've added the following code to create and activate the 'Mode Picker' and the 'todayButton' in the nav bar:

	/* Mode Picker */
	NSArray *items = @[NSLocalizedString(@"Month", @"A title for the month view button."), NSLocalizedString(@"Week",@"A title for the week view button."), NSLocalizedString(@"Day", @"A title for the day view button.")];
	
	[self setModePicker:[[UISegmentedControl alloc] initWithItems:items]];
	[[self modePicker] addTarget:self action:@selector(modeChangedUsingControl:) forControlEvents:UIControlEventValueChanged];
	[[self modePicker] setSelectedSegmentIndex:1];
	
	/* Toolbar setup */
	NSString *todayTitle = NSLocalizedString(@"Today", @"A button which sets the calendar to today.");
	UIBarButtonItem *todayButton = [[UIBarButtonItem alloc] initWithTitle:todayTitle style:UIBarButtonItemStyleBordered target:self action:@selector(todayButtonTapped:)];
	UIBarButtonItem *item = [[UIBarButtonItem alloc] initWithCustomView:[self modePicker]];
	
	[self setToolbarItems:@[todayButton, item] animated:NO];
	[[self navigationController] setToolbarHidden:NO animated:NO];
	
	/* Remove bar translucency. */
	self.navigationController.navigationBar.translucent = NO;
	self.navigationController.toolbar.translucent = NO;

But when clicking the 'Today' button, or changing the 'Mode Picker', nothing happens.

**Comment by kiahop** [comment]
Still haven't been able to get the 'Today' button to work.  I looked at the sample project code and copied the code above, and when clicking on Today button, I can trace the code into the setDate() method, but it simply does not change the date.  The method todayButtonTapped() is:
- (void)todayButtonTapped:(id)sender {
	[[self calendarView] setDate:[NSDate date] animated:YES];

Certainly I'm missing something in the settings, but tried to download the sample project a few times to compile and run, but get these errors.  I'm certain once the sample code is running, I should able to find the missing part in my code.  Any assistant is greatly appreciated:
![screen shot 2015-03-04 at 8 58 34 pm](https://cloud.githubusercontent.com/assets/10413220/6499513/85268f92-c2b1-11e4-9879-af738ab6b779.png)

**Comment by MosheBerman** [comment]
The sample project used to link correctly using modules. Apparently you have to link QuartzCore, CoreGraphics, and UIKit manually.

**Comment by jarrillaga** [comment]
Hi Moshe ! Congratulations for your nice work. I´m having the same problem that Kiahop described. I downloaded the demo project and when I compile I am getting the linking problems. I have already linked the CoreGraphics and UIKit libraries in the Link binary with libraries but the problem continues. Is it possible that you help me with this ? I would really appreciate it.

**Comment by jarrillaga** [comment]
Kiahop, you have to link QuartCore, UIKit and CoreGraphics in the MBCalendarKitTest target. After doing this, the project will compile. Cheers !

**Comment by kiahop** [comment]
jarrillaga,  apparently linking the libraries to the MBCalendarKit doesn't work, which is what I was doing!  Thanks for pointing out that 'one' thing that made it work.
