### ISSUE TITLE
1st feb

### ISSUE THREAD

**Issue by ghost** [MosheBerman/MBCalendarKit#73]
First of feb is not visible
![screen shot 2015-03-04 at 2 12 17 pm](https://cloud.githubusercontent.com/assets/7280349/6483344/834de096-c278-11e4-9f74-7fd3d7365c2d.png)

**Comment by MosheBerman** [comment]
Noted. I'll look into this one. I suspect it has to do with which day the week starts on, but I'm not certain. Just a hunch.

**Comment by MosheBerman** [comment]
I wonder if this is an issue related to #110, where non-English languages/locales are having this issue.

**Comment by MosheBerman** [comment]
This should be fixed in 5.1.0. Please let me know if this is the case.
