### ISSUE TITLE
Please suggest 2 things

### ISSUE THREAD

**Issue by tikamchandrakar18** [MosheBerman/MBCalendarKit#74]
1>If we have event in current date , so with out click on the current date we want to show the event information.

2> Can we use the today , week , month segment inside of my own view controller class , 

To use below code : 
 CKCalendarView *calendar = [CKCalendarView new];
    
    // 2. Optionally, set up the datasource and delegates
    [calendar setDelegate:self];
    [calendar setDataSource:self];
    
    [self.view addSubview:calendar];
3> How we can CKCalendarViewControllerInternal screen . We need to add the back button and navigation image  for better ui , when  user click back then we can back on own viewcontroller class.

I am unable to add the back button and give the action to come back.

Please suggest above three comments.. 

Thanks 
Tikam

**Comment by MosheBerman** [comment]
1. I'm not sure what you're asking. (If you're asking about issue #23 and #57, please see those issues.) 
2. Those buttons are just setting the `displayMode` property on the calendar view. You can implement that yourself.
3. Import the `CKCalendarViewControllerInternal.h` header. The primary difference between the `CKCalendarViewControllerInternal` and `CKCalendarViewController` is that `CKCalendarViewController` subclasses `UINavigationController`.

**Comment by tikamchandrakar18** [comment]
Thanks
I got the solution. I will let inform after app come on app store,,
