### ISSUE TITLE
Day View Event Can't be selected

### ISSUE THREAD

**Issue by bocodigital** [MosheBerman/MBCalendarKit#75]
Using CalendarView then switching to CKCalendarViewModeDay then click on event in event table view 
(void)calendarView:(CKCalendarView *)CalendarView didSelectEvent:(CKCalendarEvent *)event

does not fire, works in CKCalendarViewModeMonth and CKCalendarViewModeWeek

**Comment by bocodigital** [comment]
When i add multiple events on the day i can click the lower ones, looks like the Month navigation has a hidden layer covering the first event in the list in day view

**Comment by bocodigital** [comment]
in CKCalendarView.m 

I changed
 if(displayMode == CKCalendarViewModeDay)
    {
        //  Hide the cells entirely and only show the events table
        rect = CGRectMake(0, 0, rect.size.width, cellSize.height);
    }


to

 if(displayMode == CKCalendarViewModeDay)
    {
        //  Hide the cells entirely and only show the events table
        rect = CGRectMake(0, 0, rect.size.width, cellSize.height-60);
    }

which I will admit is hacky but it fixed the issue.

**Comment by MosheBerman** [comment]
Hey,

Thanks for reporting the issue. Are you using auto layout? Can you please provide screenshots? Also, what lines did you edit in CKCalendarView.m?

Thanks,
Moshe

**Comment by bocodigital** [comment]
I am using autolayout line 228. Also I am using Socket.IO-Client-Swift which requires IOS 8.0 or higher and a lot of the NSCalendar Unit properties are deprecated just FYI. Looks like a pretty simple re-tool, just a little tedious.

**Comment by MosheBerman** [comment]
Yeah, I thought I fixed the deprecations already, but I'll get on that soon. The auto layout is a little trickier, since I'm doing my own cells recycling. I'm concerned about recreating constraints and performance.

**Comment by MosheBerman** [comment]
MBCalendarKit 5.0.0 is out with Auto Layout and other fixes that likely cover this. If it's still relevant to you, check it out. If not, would you mind if I close this issue?
