### ISSUE TITLE
Swipe to change Months and weeks

### ISSUE THREAD

**Issue by narendra-ct** [MosheBerman/MBCalendarKit#77]
Hello,

I'm using this calendarKit it was awesome and i had a problem on the following can you please help.

- is there any way to swipe to change months in month view and swipe to change weeks on week view ?
- how can i customise the event displaying as a single DOT but here i want to change  to number of dots based on events count ?

Thanks,
Narendra V

**Comment by MosheBerman** [comment]
Hey.

• You can add a UIGestureRecognizer to the calendar view. It might confuse people, but feel free to try it.
• The cells don't support multiple dots right now, but I would look at the cell class for this. You have to think about how many dots you would show, because the cells are pretty small.

**Comment by narendra-ct** [comment]
thanks for the reply, im trying to customise the cell and i have to display dots or line graph based on events count.Can you please look at the code from your side also. If you arrange that feature that will be great.

**Comment by narendra-ct** [comment]
Hello,

i had solved my above mentioned issues thanks for your support.

Here i need a help by seleting month to weekview animation is not proper but from weekview to month view transition animation was perfect can you please have a look on it.(Here Animated should be Yes).

thanks.

**Comment by MosheBerman** [comment]
Can you show some code? What's broken about the animation?

**Comment by narendra-ct** [comment]
[self setDisplayMode:displayMode animated:YES];

If i use this to change to week/month view the frame it self changing properly but when Month to Week transition only tableview frame animation (going Up animation) is showing , CalendarView frame directly sitting on top with out any animation.

- (void)layoutSubviewsAnimated:(BOOL)animated in this method frames are setting and [self setFrame:frame animated:animated];  this used for animation.

**Comment by MosheBerman** [comment]
Ah, you're talking about the black background behind the calendar cells?

**Comment by narendra-ct** [comment]
Actually NO, i given that black baground i'm talking about cells moving animation.
while coming down (week to month) its pretty clear that cells are moving down or creating , while its moving from month to week the cella are directly setting into weekView instead any cell moving animation , here only tableview is having animation like its moving up

**Comment by MosheBerman** [comment]
Ah, I see. I never considered that to be a bug, but I'll keep it in mind for future updates.

**Comment by narendra-ct** [comment]
Thanks for the update.

A small suggestion is there any way to change the background (lighter) color for the weekend days or weekend column as SAT &amp; SUN it would be nice if we have this feature.Is there any way you just refer me i can try it out.

**Comment by MosheBerman** [comment]
Very interesting idea - not right now. You can play with the cell class, because that's where the colors are, or you may want to play with the calendar view and test the day of the week when rendering. Then, make the alpha a little lighter.

**Comment by narendra-ct** [comment]
I done with a temp fix  .

    if (self.index == 0 || self.index == 7 || self.index == 14 || self.index == 21 || self.index == 28 || self.index == 35 || self.index == 6 || self.index == 13 || self.index == 20 || self.index == 27 || self.index == 34 || self.index == 41) {
        [self setBackgroundColor:[self weekendBackgroundColor]];
    }

i think you can optimize this.

**Comment by MosheBerman** [comment]
Ah, that's neat. I've been keeping an eye on this repo for a while, but other responsibilities have me too busy to make changes. I'd probably suggest checking the NSDateComponents weekday of the cell, but I don't remember if that's accessible in the rendering loop.

**Comment by aanchalkalani** [comment]
Hi,

@narendra-ct , Could you please help us now how you manage to Swipe to change months in month view and swipe to change weeks on week view ?

Thanks,
