### ISSUE TITLE
Does anyone know of the best way to implement slide delete with an Event?

### ISSUE THREAD

**Issue by griffind** [MosheBerman/MBCalendarKit#79]

**Comment by MosheBerman** [comment]
Slide to delete is a native iOS 8 API. Even so, it's not exposed by the calendar view, so you're going to have to extend it and implement your own custom actions. 

Look at `tableView: editActionsForRowAtIndexPath:` and the `UITableViewRowAction` class. You can use those APIs to implement your delete event natively on iOS 8. To support iOS 7, look for a good open source reproduction, such as the one described here: http://www.teehanlax.com/blog/reproducing-the-ios-7-mail-apps-interface/

The calendar view still won't give you the access you're looking for, but once you're modifying the table view, you can choose between the APIs I've described.

**Comment by MosheBerman** [comment]
Also, for questions about MBCalendarKit that aren't bugs or feature requests, use the [`mbcalendarkit`](http://stackoverflow.com/questions/tagged/mbcalendarkit) tag on StackOverflow.

**Comment by griffind** [comment]
@MosheBerman Opps! Ill do that from now on. Sorry.

**Comment by MosheBerman** [comment]
No worries! Feel free to email me with any questions.
