### ISSUE TITLE
Weekview animation Enhancement

### ISSUE THREAD

**Issue by Renu-k** [MosheBerman/MBCalendarKit#80]
Hi Moshe,

I'm very happy to use this library on my project, thanks for giving such a wonderful library but here in WEEKVIEW if i change the week by clicking forward/backward weeks are changing directly without any 
" effect " or transition it is not that smooth to see also, can you please give any idea to implement sliding transition while changing the week (same like change months but in month view its Vertical transition in Weekview need horizontal scroll or transition effect).

Thans,
Renu.

**Comment by Renu-k** [comment]
Hi Moshe,

is it possible to add paging or scrolling animation on weekView while changing the week ?

Please help me on this.

Thanks,

**Comment by MosheBerman** [comment]
I'm going to keep this in mind.

**Comment by MosheBerman** [comment]
This is implemented in 5.0.0. You can turn this on by setting `animatesWeekTransitions`  to `YES` on your calendar view.

**Comment by narendra-ct** [comment]
Hi Moshe,
I hope you are doing good,
Yes with 5.1.0, the week to week transitions are working with animation. thanks for this.
I feel still the transition was not smooth when change from month to week view. In case of week to month view animation look great, but in month to week.Please refer the video  LINK you can find the gaps while transitioning from month to week.

https://www.dropbox.com/s/yvesejmb3s9pzn9/Untitled.mov?dl=0

Thanks again.
