### ISSUE TITLE
(UIColor *)toColor give error: Expected a type.

### ISSUE THREAD

**Issue by derick182** [MosheBerman/MBCalendarKit#81]
Hi,
I found this error on Swift and solved adding the #import of UIKit together with the Import of foundation.

**Comment by Rhuantavan** [comment]
Just add this #import:

#import <UIKit/UIKit.h>

**Comment by ashishpatill** [comment]
Thanks alot

**Comment by MosheBerman** [comment]
No-repro as of 24c0635.
