### ISSUE TITLE
Latest Demo Not Compatible with Swift 1.2

### ISSUE THREAD

**Issue by vishw3** [MosheBerman/MBCalendarKit#91]

**Comment by YSDC** [comment]
+1

**Comment by MosheBerman** [comment]
Can you provide a crash log or something? Crashing on what software?

**Comment by vishw3** [comment]
![screen shot 2015-06-03 at 5 39 36 pm](https://cloud.githubusercontent.com/assets/10825655/7959536/911451ec-0a17-11e5-85da-27d0aaed1ab0.png)

**Comment by MosheBerman** [comment]
Ah, that's not a crash, it's a compilation error. 

Looks like a change from Swift 1.0 to 1.2. I can't make changes over the summer, but look in Xcode's "Edit" menu, there should be something there about making the change.

If someone wants to do this and make a pull request, I may be able to merge it.

**Comment by rpvilela** [comment]
You can comment all init() and change the variable declaration.
var data : NSMutableDictionary = NSMutableDictionary()

**Comment by MosheBerman** [comment]
24c0635 converts to  Swift 2.x.
