### ISSUE TITLE
Calendar View Cells issue in MonthView.

### ISSUE THREAD

**Issue by Renu-k** [MosheBerman/MBCalendarKit#92]
Hi MosheBerman,

can you please look at this,
- i'm happy to use MBCalendarKit in my project but i had one issue can you please have a look.

issue: Calendar dates cells are empty in month view.
- goto weekView and change week to next and previous continuously and then come back to month view the cells are empty but Calendar View frame has been changed.

Please see attached image to analyse the issue.

Thanks,
Renu.
![thumb_img_0891_1024](https://cloud.githubusercontent.com/assets/11937122/8055795/bac2e0ec-0ebf-11e5-9bd5-ac17b82b4921.jpg)

**Comment by MosheBerman** [comment]
This looks like a bug, but it's probably been fixed in 5.0.0, because cell layout is completely different now.

**Comment by MosheBerman** [comment]
Version 5 is out now.
