### ISSUE TITLE
Multiple deprecation warnings

### ISSUE THREAD

**Issue by UberJason** [MosheBerman/MBCalendarKit#96]
Hi Moshe,

I've noticed multiple deprecation warnings for iOS 8+ regarding the calendar unit flags. Examples include NSSecondCalendarUnit (use NSCalendarUnitSecond instead), NSMinuteCalendarUnit, NSHourCalendarUnit, ...

Most of these are pretty easily changed, although NSWeekCalendarUnit needs to become either NSCalendarUnitWeekOfMonth or NSCalendarUnitWeekOfYear. You're probably better qualified than I to go through and make those changes. (And yes, I did open an issue about this months ago, and you fixed a few instances of it - which I appreciate! But I found more of them. :) )

**Comment by MosheBerman** [comment]
Interesting. I'll do my best to clean this up. Been a wild summer and fall, but I gotta give my code a pass through and bring up to speed. Thanks for filing this.

**Comment by MosheBerman** [comment]
Fixed this with 24c0635.
