### ISSUE TITLE
Initializer does not override a designated initializer from its superclass?

### ISSUE THREAD

**Issue by Nandulucky** [MosheBerman/MBCalendarKit#99]
Hi,

I'm working on calendar with events using MBCalendarKit, but it's shows 2 warnings below.

1) Initializer does not override a designated initializer from its superclass.
2) Must call a designated initializer of the superclass 'CKDemoViewController'.

How can i resolve this. Please help me.
Thanks in Advance.

-Nandu

**Comment by MosheBerman** [comment]
I just pushed an update for the latest Swift syntax. Let me know if this fixes it for you.

**Comment by MosheBerman** [comment]
No reply and 5.0.0 is out, closing this.
